About
NovicovMykhailo/icecream_team_project pull request #6
Opened 2022-12-23 08:21 UTC by HannaPo

2022-12-23 12:02 UTC, NovicovMykhailo requested changes

2022-12-23 12:02 UTC, NovicovMykhailo commented on src/sass/sections/_about.scss
> +  letter-spacing: 0.04em;
не того розміру текст на десктопі та плашеті (
font-size: 16px;
line-height: 28px;
, треба добавити медіа правило

2022-12-23 12:02 UTC, NovicovMykhailo commented on src/sass/sections/_about.scss
> +  fill: currentColor;
треба стрілочку передивитись, я чомусь її не бачу((

2022-12-23 12:02 UTC, NovicovMykhailo commented on src/sass/sections/_about.scss
> +.about {
на планшеті не там картинка стає, в неї якісь дивні марджини ао боках, кнопка не на тому місці в планшетній версії. мобільна версія ламається. на кнопках треба падінги перебити падінги додатковим класом

2022-12-23 21:07 UTC, HannaPo commented on src/sass/sections/_about.scss
> +.about {
Наче все виглядає по макету, тільки не знаю, що робити з мобільною версією при зменшенні

2022-12-24 00:43 UTC, NovicovMykhailo approved these changes

2022-12-24 00:44 UTC, merged